behaviors:
  fighterBrain:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 256
      buffer_size: 8192
      learning_rate: 1.0e-4
      learning_rate_schedule: constant
      

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 6e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 1024
      num_layers: 4
      use_recurrent: true
      # memory
      memory:
        sequence_length: 8
        memory_size: 512

    # Trainer configurations common to all trainers
    max_steps: 500000000
    time_horizon: 128
    summary_freq: 20000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    #init_path: results/Curi_RND15e3F4/fighterBrain

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.992
        network_settings:
            hidden_units: 512
            num_layers: 4
        
      # curiosity module
      curiosity:
        strength: 0.05
        gamma: 0.992
        learning_rate: 5e-4
        network_settings:
            hidden_units: 512
            num_layers: 4
      
      #RND Instric Reward
      #rnd:
      #  strength: 0.005
      #  gamma: 0.995
      #  learning_rate: 4e-4
        
      #gail:
      #  strength: 0.4
      #  demo_path: Demos/singleDogFight.demo
        #use_actions: true
    
    #behavioral_cloning:
    #  strength: 0.25
    #  demo_path: Demos/singleDogFight.demo
      # GAIL
      #gail:
      #  strength: 0.01
      #  gamma: 0.99
      #  #demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
      #  learning_rate: 3.0e-4
      #  use_actions: false
      #  use_vail: false
      
    #self_play:
    #    window: 30
    #    play_against_latest_model_ratio: 0.5
    #    save_steps: 40000
    #    swap_steps: 10000
    #    team_change: 100000